"""
Temporary mock OCR / document-understanding layer.

This module stands in for Amazon Textract until the AWS integration phase.
Swap `extract_text_from_image` for a Textract-backed implementation
(e.g. `extract_text_with_textract(image_path) -> str`) without changing
any caller - the function signature is the contract.
"""

DEMO_DOCUMENT_TEXT = """Patient Name: Ramesh Kumar
Age: 65
Document Type: Medical Report

Medical Information:
The patient reports symptoms related to respiratory allergies.

Note: This is fictional demonstration data only, generated by a mock OCR
service for prototype testing. It is not a real prescription or diagnosis."""


def extract_text_from_image(image_path: str) -> str:
    """
    Temporary mock OCR implementation.
    This will later be replaced with Amazon Textract.
    """
    return DEMO_DOCUMENT_TEXT
